### ISSUE TITLE
Optional task is unfinished

### ISSUE THREAD

**Issue by vforvasile** [Dimasprog/Planable#1]
Hi!

Good job with the task!

Based on the provided GIF in README I noticed that the details screen does not render the **photo** as mentioned in the requirements: 

> Add EXIF info about photo **below the image** using photo id. (You'll need to use Get a photo endpoint here.)

As a suggestion:
- Create a new branch called: **fix/photo-screen**; 
- Make the changes to apply the missing requirements above;
- Open a Pull Request and provide a PR link. 

Good luck!

**Comment by Dimasprog** [comment]
Hi, thank you for review!

**Comment by Dimasprog** [comment]
Hi, thank you for review!

So, as i understand, on second screen i have to render the **photo** and the **photo EXIF** through API based on photo id, right?

**Comment by vforvasile** [comment]
You can either use an API call through photo id or pass to navigation params or use your own technique, it's your call.

The EXIF data should be rendered below the **Photo**.

**Comment by Dimasprog** [comment]
Ok, got it!

**Comment by Dimasprog** [comment]
I created a pull request. Check it out.

**Comment by Dimasprog** [comment]
Here is link to PR -> https://github.com/Dimasprog/Planable/pull/2
